name: Build & Test BearOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential qemu-system-x86 nasm gcc

      - name: Build BearOS
        run: |
          make iso
      

      - name: Compile Code
        run: |
          make compile
